Driver service
ZhVladislav9/cab-aggregator-app pull request #5
Opened 2024-01-24 09:45 UTC by ZhVladislav9

2024-02-01 08:55 UTC, pij1989 requested changes

2024-02-01 08:55 UTC, pij1989 commented on driver-service/src/main/java/com/driverservice/driverservice/service/Impl/DriverServiceImpl.java
> +    public DriversListResponse getDriversList(Integer offset, Integer page, String sortByField) {
getDriversList и getAvailableDriversList - здесь очень много дублирования кода, и работу с пагинацией хотелось бы вынести в отдельный утилитный класс. Например: 
```suggestion
     public DriversListResponse getDriversList(Integer offset, Integer page, String sortByField) {
        Pageable pageable = PaginationUtil.createPageRequest(offset, page, sortByField, DriverResponse.class);
        if (pageable.isPaged()) {
            return getListWithPagination(driverRepository.findAll(pageable)
                    .map(driverDtoConverter::convertDriverToDriverResponse), sortByField);
        }
        return getList(driverRepository.findAll(pageable.getSort()).stream()
                .map(driverDtoConverter::convertDriverToDriverResponse)
                .toList(), sortByField);
    }

    public DriversListResponse getAvailableDriversList(Integer offset, Integer page, String sortByField) {
        Pageable pageable = PaginationUtil.createPageRequest(offset, page, sortByField, DriverResponse.class);
        if (pageable.isPaged()) {
            return getListWithPagination(driverRepository.findAllByIsAvailableIsTrue(pageable)
                    .map(driverDtoConverter::convertDriverToDriverResponse), sortByField);
        }
        return getList(driverRepository.findAllByIsAvailableIsTrue(pageable.getSort()).stream()
                .map(driverDtoConverter::convertDriverToDriverResponse)
                .toList(), sortByField);
    }

    private DriversListResponse getListWithPagination(Page<DriverResponse> responsePage, String sortByField) {
        return DriversListResponse.builder()
                .drivers(responsePage.getContent())
                .sortedByField(sortByField)
                .size(responsePage.getContent().size())
                .page(responsePage.getPageable().getPageNumber())
                .total((int) responsePage.getTotalElements())
                .build();
    }

    private DriversListResponse getList(List<DriverResponse> responseList, String sortByField) {
        return DriversListResponse.builder()
                .drivers(responseList)
                .sortedByField(sortByField)
                .total(responseList.size())
                .build();
    }
```
И отдельный класс для пагинации:
```suggestion
    @UtilityClass
public class PaginationUtil {

    public static <T> Pageable createPageRequest(Integer offset, Integer page, String sortByField, Class<T> clazz) {
        Sort sort = Sort.unsorted();
        if (Objects.nonNull(sortByField)) {
            validateSortingParameter(sortByField, clazz);
            sort = Sort.by(sortByField);
        }

        if (Objects.nonNull(offset) && Objects.nonNull(page)) {
            validatePaginationParameters(offset, page);
            return PageRequest.of(page, offset).withSort(sort);
        }

        return Pageable.unpaged(sort);
    }

    private void validatePaginationParameters(Integer offset, Integer page) {
        if (offset <= 0) {
            throw new InvalidRequestException(OFFSET_NOT_VALID_MESSAGE);
        }
        if (page < 0) {
            throw new InvalidRequestException(PAGE_NOT_VALID_MESSAGE);
        }
    }

    private <T> void validateSortingParameter(String sortingParam, Class<T> clazz) {
        List<String> fieldNames = Arrays.stream(clazz.getDeclaredFields())
                .map(Field::getName)
                .toList();

        if (!fieldNames.contains(sortingParam)) {
            String errorMessage = String.format(INVALID_SORTING_MESSAGE, fieldNames);
            throw new InvalidRequestException(errorMessage);
        }
    }
}
```

2024-02-02 08:18 UTC, pij1989 commented on driver-service/src/main/java/com/driverservice/driverservice/kafka/RideConsumer.java
> +        JsonNode jsonNode = objectMapper.readTree(String.valueOf(requests.get(0)));
У тебя в консьюмере указан List<RideProducerRequest> requests, а в конфиге для консьюмера в десериалайзере указан просто RideProducerRequest.class `return new DefaultKafkaConsumerFactory<>(config, new StringDeserializer(), new JsonDeserializer<>(RideProducerRequest.class));`. Скорее всего из-за этого он некорpектно десериализует лист.

2024-02-05 09:02 UTC, ZhVladislav9 commented on driver-service/src/main/java/com/driverservice/driverservice/kafka/RideConsumer.java
> +        JsonNode jsonNode = objectMapper.readTree(String.valueOf(requests.get(0)));
Да, я понимаю. Но даже если будут одинаковые значения оно все равно приходит в Json. А если в консъюмере не указать List, то вообще выбрасывает исключение.

2024-02-06 06:47 UTC, pij1989 approved these changes

2024-02-07 13:51 UTC, merged