Rides service
ZhVladislav9/cab-aggregator-app pull request #6
Opened 2024-01-24 09:46 UTC by ZhVladislav9

2024-01-30 10:03 UTC, AbandonedScope requested changes

2024-01-30 10:03 UTC, AbandonedScope commented on rides-service/src/main/java/com/ridesservice/ridesservice/util/RidesFeignClient.java
> +@FeignClient(value = "FeignClient", url = "http://localhost:8094/api/v1/passenger")
Читай url из application.properties

2024-01-30 10:03 UTC, AbandonedScope commented on rides-service/src/main/resources/application.yml
> +
Лишние пустые строки

2024-01-30 16:38 UTC, ZhVladislav9 commented on rides-service/src/main/java/com/ridesservice/ridesservice/service/Impl/RideServiceImpl.java
> +        if (ride != null) {
Этот метод вызывается, когда приходит запрос, что появился свободный водитель. Если поездка не нашлась, то ничего не происходит

2024-01-30 16:41 UTC, ZhVladislav9 commented on rides-service/src/main/java/com/ridesservice/ridesservice/kafka/DriverConsumer.java
> +        }
Здесь обрабатывается запрос из Kafka. Он у меня приходит только в формате JSON, а по-другому у меня никак не получилось сделать

2024-01-30 17:44 UTC, AbandonedScope requested changes

2024-01-30 17:44 UTC, AbandonedScope commented on rides-service/src/main/java/com/ridesservice/ridesservice/controllers/RideController.java
> +    }
Логики в контроллерах быть не должно
Я имел ввиду, что ты можешь отправлять Patch запрос на смену статуса просто

2024-01-30 17:44 UTC, AbandonedScope commented on rides-service/src/main/java/com/ridesservice/ridesservice/convert/RideDtoConverter.java
> +
```suggestion
```

2024-01-30 17:44 UTC, AbandonedScope commented on rides-service/src/main/java/com/ridesservice/ridesservice/exceptions/handler/RideExceptionHandler.java
RideNotFoundException, PromoCodeNotFoundException, NoAvailableRidesException, FeignClientException - в один обработчик объедини, и то же самое с методами, которые возвращают BAD_REQUEST(кроме обрабатывающего валидационные ошибки, его можно оставить отдельно)

2024-02-05 08:50 UTC, AbandonedScope commented on rides-service/src/main/java/com/ridesservice/ridesservice/service/Impl/RideServiceImpl.java
> +                .build();
Вот это лучше вынести в отдельный метод конечно

2024-02-05 08:56 UTC, merged